create table id not exists users( id integer primary key AUTOINCREMENT, name text not null, password text not null, admin boolean not null DEFAULT '0');


create table  if not exists emp ( empid integer primary key AUTOINCREMENT, name text not null, email text, phone integer, address text, joining_date timestamp DEFAULT CURRENT_TIMESTAMP,  total_projects integer default 1, total_test_case integer DEFAULT 1, total_defects_found integer DEFAULT 1, total_defects_pending integer DEFAULT 1 );


CREATE TABLE if not exists testcase(tescaseid integer primary key autoincrement ,
testcasename text, requirementnumber text , modulename text , buildnumber text , precondition text , testdata text, postcondition text, severity text , testcasetype text , briefdescription text , textcaseexecutionhours text,
stepnumber1 text ,
 action1 text,
testdata1 text ,
expectedresult1 text,
actualresult1 text,
status1 text ,
remark1 text ,
stepnumber2 text ,
 action2 text,
testdata2 text ,
expectedresult2 text,
actualresult2 text,
status2 text ,
remark2 text ,
stepnumber3 text ,
 action3 text,
testdata3 text ,
expectedresult3 text,
actualresult3 text,
status3 text ,
remark3 text ,
stepnumber4 text ,
 action4 text,
testdata4 text ,
expectedresult4 text,
actualresult4 text,
status4 text ,
remark4 text ,
stepnumber5 text ,
 action5 text,
testdata5 text ,
expectedresult5 text,
actualresult5 text,
status5 text ,
remark5 text ,
stepnumber6 text ,
 action6 text,
testdata6 text ,
expectedresult6 text,
actualresult6 text,
status6 text ,
remark6 text ,
authorname text , reviewedby text, approvedby text, approvaldate datetime);
